### ISSUE TITLE
Command line switches (to upload silently)

### ISSUE THREAD

**Issue by sergeevabc** [bkeiren/EasyImgur#11]
Dear Bryan,
command line switches of EasyImgur are not documented,
I am not even sure how many of them actually exist, but
here is a typical scenario I'd like to accomplish: 

`EasyImgur.exe /silent /exit %1`
- app uploads some file with no tray bubbles
- app puts uploaded file link into clipboard
- app closes

Is it possible now, or in the near future?

**Comment by snoozbuster** [comment]
Adding an `/exit` switch is easy, and I could submit a pull request for that right now. I wouldn't mind adding a `/silent` switch but I'm not sure how it should work. For example: if an error occurs, should EasyImgur ignore the `/silent` switch and display the error anyway? EasyImgur is single-instanced, so if you launch another instance it will simply pass its arguments to the original instance and terminate. In that case, what happens if `/silent` is passed without `/exit`? Should EasyImgur be permanently silenced for the remainder of its lifetime, or should it only be silenced for the current batch of uploads? Additionally, since EI just processes arguments as it sees them, instead of scanning the whole list, `/silent` would function like `/anonymous` in that it would only apply to arguments after it. I'd be happy to implement the switch if someone clarifies how exactly it should work.

**Comment by bkeiren** [comment]
I would imagine that passing `/silent' alongside a number of arguments should only apply to those arguments (though what if the 'master' instance was opened with `/silent', do we still enforce this even if it later receives non-silent arguments?).

Regarding `/anonymous' I think we might need to change the command-line parsing to consist of two passes where we first parse all commands separately and then apply modifiers such as `/anonymous' to the entire list of commands. If users want to then upload 2 files anonymously and 2 files to their account they can invoke EI twice (which is now very easy since EI is single-instanced and all).

**Comment by snoozbuster** [comment]
I could certainly change the parsing to be more robust. The only real questions then are if `/silent` should be permanent if the master instance is invoked with it, and if it should override the clipboard copy setting or follow it. Following it would be easy, but perhaps lead to unexpected behavior when it isn't enabled. Oh, and errors; should errors ignore `/silent`?

**Comment by bkeiren** [comment]
Perhaps we should implement 2 degrees of silence. It is common to be able to pick the verbosity of warnings and errors in applications, so it may be a good idea if we do the same. We could implement a `/silentinfo' and `/silenterror' (or something along those lines) to control exactly which messages are silenced. Mind that we would still want to log everything that happens.

I think that if the master instance is invoked with `/silent' other instances should still be able to override it, but the setting should be restored after the commands have been processed. I don't think any particular solution is the best in this case so it's quite difficult to say what we should do and what is expected behaviour. One of the things to keep in mind here is that users may not have started the master instance themselves. Perhaps they don't have EI running by default but boot it through a context menu option. In this case the master settings are completely arbitrary and have nothing to do with actual preferences of the users. This would be an argument against making master settings control anything except master commands.

**Comment by snoozbuster** [comment]
I think that in that light, `/silent` should only apply to the set of arguments passed in for that specific invocation. I think they should be named `/noinfo` and `/noerr`, though, or possibly `/q` and `/qq`. If both are passed the most restrictive one would take priority, I suppose.

**Comment by bkeiren** [comment]
I agree.

**Comment by snoozbuster** [comment]
Alright. Which naming convention would you prefer? I'll also add all the command line switches to the documentation, if you haven't already.

**Comment by bkeiren** [comment]
I have literally just created [this wiki page](https://github.com/bkeiren/EasyImgur/wiki/Command-Line-Parameters), so you can edit that to reflect any changes that are made. :)

I don't mind whether we name them `/noinfo` and `/noerr` or `/q` and `/qq`, so pick whichever you like. The `q` ones would make the command line not as cluttered though, so I guess there's an argument for using those ;)

**Comment by snoozbuster** [comment]
Sounds good. I'll make a pull request when I've got something ready.

**Comment by bkeiren** [comment]
Cool, looking forward to seeing it! :)

**Comment by snoozbuster** [comment]
If you want to check out the code in my `flags` branch I believe I have this working. I haven't tested it yet but I don't know if I'll have an opportunity to today so I figured I'd let you know in case you get around to it before I do.

**Comment by bkeiren** [comment]
Looks alright so far, though may I suggest renaming the `Silence` member to something more accurate such as `Verbosity`?

**Comment by snoozbuster** [comment]
Ah, that's good. I couldn't think of a good way to resolve the name collision.

**Comment by bkeiren** [comment]
Looks good, go ahead and make a pull request :)

**Comment by snoozbuster** [comment]
Opened pull request #13. You'll have to update the dists.

**Comment by bkeiren** [comment]
Implemented in [release 0.2.3](https://github.com/bkeiren/EasyImgur/releases/tag/0.2.3).
