### ISSUE TITLE
Provide a setting to make easyimgur portable

### ISSUE THREAD

**Issue by aviaryan** [bkeiren/EasyImgur#12]
It seems that EasyImgur creates folder in %appdata% and %localappdata% . Can you please provide an option to avoid that.

**Comment by bkeiren** [comment]
Hi aviaryan!

Would you mind sharing why exactly you want this behaviour changed? I can think of many reasons why you would but I'd like to hear yours.

Since the name of this issue refers to making EasyImgur portable I would like to point out that EI is already portable in the sense that you can simply run the executable whenever you want to start it, there is no installation process required (it will then indeed still store settings data in those folders though).

Here's the thing: I can't think of a good way of implementing this that I'm satisfied with. For example, we could provide an additional setting that controls this, but this would require either making `portable mode' the default or storing settings anyway. Making it the default is undesirable because users would expect settings to be saved automatically, not that EI runs in portable mode by default. Storing a setting for this is also not possible for obvious reasons (we'd be saving things, which is exactly what we wouldn't want to be doing).
Instead of providing a setting for this another possibility would be to provide separate executables. However this is also undesirable because it would effectively double the amount of testing that would have to be done. Additionally it would likely mean that we would introduce discrepancies between the portable and non-portable executables in terms of features (think of context menu options, we wouldn't be able to offer those in portable mode and have them function in an expected way). This is inconvenient and for some users highly illogical and confusing.

I would love to hear your input on the matter, because to me right now it doesn't seem like keeping EasyImgur from storing data in those folders or altering the registry (if needed) is a very desirable or required feature (with all due respect for your situation).

Cheers!

**Comment by snoozbuster** [comment]
EasyImgur originally stored the log and history databases in the local folder instead of in `%appdata%`. When I found this project and added the context menu stuff, I changed it to save into `%appdata%` because I didn't really like the files hanging around and cluttering the directory EI was in, and because that behavior meant that if you moved EI without moving its files (which weren't named in any relatable fashion and indeed could easily be lost in a large file list) you would lose your upload history. If you were to disable the "start on startup" and "enable context menu" options, the registry would be unaffected, and then if we were to add an option to "save files in local directory" or something like that, it would be "portable" in the way you're describing. We could then theoretically distribute an extra executable that only differs in its initially selected options.

**Comment by aviaryan** [comment]
> Would you mind sharing why exactly you want this behaviour changed? I can think of many reasons why you would but I'd like to hear yours.

I would like to move around with EasyImgur on my pendrive such that it is always linked to my account. This requires keeping the settings folders with the program. I just made a launcher for this and it's working great.

Another way to make this program "portable" can be just providing the setting to store settings in the local folder instead of the %appdata%. Users like me can then simply select this option and move along. Regular users may not select this option and have the settings in the APPDATA.

**Comment by bkeiren** [comment]
Aviaryan, since you're okay with keeping additional files alongside EasyImgur I'm thinking of adding the following things:

- A `-portable` command line switch.
- Embed the Newtonsoft.Json DLL so it cuts down on the number of files required to run EI (just a single file then). I have already implemented this and submitted the changes, there is no release yet that incorporates this (will do so once the -portable stuff is implemented).

Note that it's not very convenient to implement this as an option in the actual application, because how would we persist this between runs? We could store it in the actual settings file but then how will we determine whether to look for a local settings file or a normal settings file? What if we find both, which one gets precedence? 

I think the best option is to circumvent these issues entirely by simply allowing the user (you) to run EI in portable mode explicitly through a command line switch (you say you have a launcher, I'd imagine you can add it to this).

A small caveat is that in portable mode we will have to restrict certain options to keep ourselves from having to do too much management. This would include options such as the context menu or start-on-boot. I would imagine that this wouldn't be too much of an issue though.

Looking forward to hearing you guys' comments!

**Comment by snoozbuster** [comment]
I was thinking the settings were stored in the executable for some reason. But yeah, that seems like a good solution. The other option is to use an option to save files in the local directory; local settings/etc would take precedence in the event of both existing but when the setting is toggled the files would be moved (either to `%appdata%` or to the local directory, whichever is appropriate). So, it wouldn't often come up. Then the portable version of the application just has different setting defaults.

**Comment by aviaryan** [comment]
>> What if we find both, which one gets precedence?

The local one ?? But then yes, this method may be logically difficult to construct.

>> I think the best option is to circumvent these issues entirely by simply allowing the user (you) to run EI in portable mode explicitly through a command line switch (you say you have a launcher, I'd imagine you can add it to this).

:+1:  That would be very convenient .

**Comment by bkeiren** [comment]
The thing is that although it may seem logical to say that the local settings have precedence if present, there may be situations where this is not the case. We have no way of knowing for sure and so I'm hesitant to select either option as *the* solution.

Anyway, I have just submitted changes to implement portable mode and will be submitting a new release shortly.

**Comment by bkeiren** [comment]
I have just released a new version (0.2.2) which includes the most recent changes and implements portable mode. The packaged release includes a simple .bat file to run EI in portable mode for convenience.

https://github.com/bkeiren/EasyImgur/releases/tag/0.2.2
