### ISSUE TITLE
add hotkeys support

### ISSUE THREAD

**Issue by jt3k** [bkeiren/EasyImgur#34]
for example - hot key for select the area of the screen

**Comment by AWSM3** [comment]
Yeah, that's really desired functioonality. Like Ctrl + Shift + 4 in Hyperdesktop.

**Comment by bkeiren** [comment]
Thank you for your suggestion! 

Screenshotting a part of the screen is nowadays natively supported by Windows (Hotkey: WIN + SHIFT + S), which places the screenshot on the Windows clipboard. Since EasyImgur supports uploading directly from the Windows clipboard, this should provide the functionality requested, therefore we are closing this request.
