### ISSUE TITLE
Did this project still alive?

### ISSUE THREAD

**Issue by Cologler** [bkeiren/EasyImgur#43]
Why no body watch my pull requests ?

**Comment by ThiefMaster** [comment]
I'm not involved with this project but if I were I'd reject it because you mix refactoring with real changes. Refactoring is fine, after discussed with the developers of the project, and if done separately. But here you have a +-1000 line PR where it looks like most of the changes are just refactoring...

**Comment by Cologler** [comment]
@ThiefMaster the PR was created at 2016-02-13, and the refactoring was commited at 2016-05-26.

**Comment by cxcorp** [comment]
It's quite a project to look through the pull request. I would suggest separating (by cherry-picking or an interactive rebase) the real changes from the refactorings into different branches and PRs. I would also recommend naming the commits so that it's easy to see what it is about, why it was made, and what it fixes. Try bunching related refactorings into the same commit - for example if there's one where you remove all unrelated `using`s, that could be one. One could be one where you remove unnecessary namespace uses, e.g. `System.Collections.Generic.List` -> `List`.
